-- # 个股日线基础因子数据表
drop table if exists `factor_basic_info`;
CREATE TABLE `factor_basic_info` ( 
  `name` varchar(256) NOT NULL COMMENT '因子名称', 
  `desc` text DEFAULT NULL COMMENT '因子描述',
  `source` VARCHAR(256) NOT NULL COMMENT '因子源',
  `type` int DEFAULT NULL COMMENT '因子类型',
  `scope` int DEFAULT NULL COMMENT '范围',
  `status` int DEFAULT NULL COMMENT '状态',
  `remark` text DEFAULT NULL COMMENT '备注',
  `update_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `create_time` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`name`,`source`),
  INDEX `IDX_CODE` (`name`),
  INDEX `IDX_DATE` (`source`),
  INDEX `IDX_ISST` (`status`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_001","(-1 * CORR(RANK(DELTA(LOG(VOLUME), 1)), RANK(((CLOSE - OPEN) / OPEN)), 6)) ","GTJA_191",1,1,1,"刻画成交量变化排名与日内收益率排名的偏离程度，表现为成交量变化排名上升，日内收益率排名下降；成交量变化排名下降，日内收益率排名上升。");

INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_002","-1 * delta((((close-low)-(high-close))/((high-low)),1))","GTJA_191",1,1,1,"刻画多空失衡变动情况，用(CLOSE - LOW) - (HIGH - CLOSE)) / (HIGH - LOW)表示多空力量不平衡度。");

INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_003","SUM((CLOSE=DELAY(CLOSE,1)?0:CLOSE-(CLOSE>DELAY(CLOSE,1)?MIN(LOW,DELAY(CLOSE,1)):MAX(HIGH,DELAY(CLOSE,1)))),6)","GTJA_191",1,1,1,"收盘价对比");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_004","((((SUM(CLOSE,8)/8)+STD(CLOSE,8))<(SUM(CLOSE,2)/2))?(-11):(((SUM(CLOSE,2)/2)<((SUM(CLOSE,8)/8)-STD(CLOSE,8)))?1:(((1<(VOLUME/MEAN(VOLUME,20)))||((VOLUME/MEAN(VOLUME,20))==1))?1:(-11))))","GTJA_191",1,1,1,"区间突破因子。价格（2日均价）突破布林带（8日）上限取-1，价格突破布林带下限取1,价格在布林带区间内时，成交量放大或不变取1，成交量缩小取-1");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_005","(-1*TSMAX(CORR(TSRANK(VOLUME,5),TSRANK(HIGH,5),5),3))","GTJA_191",1,1,1,"短期（3天）内成交量、高点最大偏离程度表现为短周期内（5天）成交量上升，最高价下降；或者成交量下降，最高价上升。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_006","(RANK(SIGN(DELTA((((OPEN0.85)+(HIGH0.15))),4)))*-1)","GTJA_191",1,1,1,"可能是在刻画当前价格位置和此前位置价格的差距，进行动量交易，具体意义不明。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_007","((RANK(MAX((VWAP-CLOSE),3))+RANK(MIN((VWAP-CLOSE),3)))*RANK(DELTA(VOLUME,3)))","GTJA_191",1,1,1,"刻画收盘价和3日均价的关系部分结果和JQaunt 一直，但总会有一些结果不一致，暂时找不到原因"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_008","RANK(DELTA(((((HIGH + LOW) / 2)0.2) + (VWAP * 0.8)), 4) - 1","GTJA_191",1,1,1,"横截面对比"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_009","SMA(((HIGH+LOW)/2-(DELAY(HIGH,1)+DELAY(LOW,1))/2)*(HIGH-LOW)/VOLUME,7，2)","GTJA_191",1,1,1,"非横截面对比"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_010","(RANK(MAX(((RET<0)?STD(RET,20):CLOSE)^2),5))","GTJA_191",1,1,1,"20日收益率波动和收盘价对比"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_011","(SUM(((CLOSE-LOW)-(HIGH-CLOSE))./(HIGH-LOW).*VOLUME,6)","GTJA_191",1,1,1,"计算一个基于价格变化和交易量加权的指标，以衡量过去6天内价格动力或强度的累积效果"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_012","(RANK((OPEN-(SUM(VWAP,10)/10))))(-1(RANK(ABS((CLOSE-VWAP)))))","GTJA_191",1,1,1,"衡量开盘价相对于过去10天VWAP的平均值的相对位置."); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_013","(((HIGH*LOW)^0.5)-VWAP)","GTJA_191",1,1,1,"计算了当日最高价和最低价的几何平均值与当日VWAP之间的差值。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_014","CLOSE-DELAY(CLOSE,5) ","GTJA_191",1,1,1,"计算当前收盘价与5天前的收盘价之间的差值。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_015"," OPEN/DELAY(CLOSE,1)-1","GTJA_191",1,1,1,"表示了开盘价相对于前一天收盘价的相对变化率。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_016","(-1*TSMAX(RANK(CORR(RANK(VOLUME),RANK(VWAP),5)),5))","GTJA_191",1,1,1,"分析交易量（VOLUME）和VWAP之间的关系，并计算这种关系在过去5天内的最大排名（经过反转）。这可能用于识别交易量和VWAP之间关系的重要变化或转折点，从而帮助投资者做出决策。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_017","RANK((VWAP-MAX(VWAP,15)))^DELTA(CLOSE,5)","GTJA_191",1,1,1,"当前VWAP相对于其近期最高点的位置在历史上的相对排名。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_018"," CLOSE / DELAY(CLOSE, 5)","GTJA_191",1,1,1,"当前VWAP相对于其近期最高点的位置在历史上的相对排名。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_019","(CLOSE < DELAY(CLOSE, 5)?(CLOSE-DELAY(CLOSE, 5)) / DELAY(CLOSE, 5): (CLOSE=DELAY(CLOSE, 5)?0: (CLOSE - DELAY(CLOSE, 5)) / CLOSE))","GTJA_191",1,1,1,"如果当前周期的收盘价小于5个周期前的收盘价，返回相对跌幅（(CLOSE - DELAY(CLOSE, 5)) / DELAY(CLOSE, 5)）。如果当前周期的收盘价等于5个周期前的收盘价，返回0。如果当前周期的收盘价大于5个周期前的收盘价，返回相对涨幅（(CLOSE - DELAY(CLOSE, 5)) / CLOSE）"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_020","(CLOSE-DELAY(CLOSE,6))/DELAY(CLOSE,6)*100","GTJA_191",1,1,1,"当前周期的收盘价（CLOSE）相对于6个周期前的收盘价（DELAY(CLOSE, 6)）的百分比变化"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_021","REGBETA(MEAN(CLOSE,6),SEQUENCE(6))","GTJA_191",1,1,1,"找出过去6个交易日收盘价的平均值与这些交易日序号之间的线性关系。如果REGBETA的结果为正，这可能意味着收盘价在近期有上升的趋势；如果为负，则可能表示有下降的趋势。然而，这种分析方法的解释和有效性取决于具体的应用场景和数据特性。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_022","SMEAN(((CLOSE-MEAN(CLOSE,6))/MEAN(CLOSE,6)-DELAY((CLOSE-MEAN(CLOSE,6))/MEAN(CLOSE,6),3)),12,1)","GTJA_191",1,1,1,"首先，计算当前收盘价与过去6个交易日收盘价的平均值的标准化差值。然后，获取这个标准化差值在3个交易日前的值。最后，计算这个延迟后的标准化差值在过去12个交易日内的简单移动平均值。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_023","SMA((CLOSE > DELAY(CLOSE, 1)?STD(CLOSE:20), 0), 20, 1) / (SMA((CLOSE > DELAY(CLOSE, 1)?STD(CLOSE, 20):0), 20, 1)+SMA((CLOSE <= DELAY(CLOSE, 1)?STD(CLOSE, 20): 0), 20, 1))*100","GTJA_191",1,1,1,"该指标基于当前收盘价相对于昨日收盘价的变动情况，以及价格的波动性（通过标准差来衡量）。具体来说，它可能是在尝试量化价格上涨时的波动性相对于总波动性的比例，并将其转换为百分比形式。"); 

INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_024","SMA(CLOSE-DELAY(CLOSE,5),5,1)","GTJA_191",1,1,1,"计算当前收盘价与5个交易日前的收盘价之间的差值，并对这个差值计算一个5日的简单移动平均。这样的指标可能用于识别价格变动的趋势或动量，从而帮助交易者做出决策。例如，如果SMA值上升，这可能意味着价格正在加速上涨；如果SMA值下降，这可能意味着价格上涨的势头正在减弱。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_025","((-1 * RANK((DELTA(CLOSE,7) * (1-RANK(DECAYLINEAR((VOLUME/MEAN(VOLUME,20)),9))))))*(1+RANK(SUM(RET,250))))","GTJA_191",1,1,1,"可能是在尝试结合价格变动、交易量以及长期回报率的信息来生成一个指标。这样的指标可能用于识别市场趋势、动量或其他交易信号。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_026","((((SUM(CLOSE, 7) / 7) - CLOSE)) + ((CORR(VWAP, DELAY(CLOSE, 5), 230))))","GTJA_191",1,1,1,"这个表达式将上述两部分相加。第一部分是当天收盘价与过去7天平均收盘价的差值，第二部分是VWAP与5天前的收盘价之间的相关性。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_027","WMA((CLOSE-DELAY(CLOSE,3))/DELAY(CLOSE,3)*100+(CLOSE-DELAY(CLOSE,6))/DELAY(CLOSE,6)*100,12)","GTJA_191",1,1,1,"算了当天收盘价与过去几天收盘价的百分比变动，并将这些变动进行加权移动平均处理。这样的计算方法可能用于捕捉短期内的价格变动趋势。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_028","3*SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1)-2*SMA(SMA((CLOSE-TSMIN(LOW,9))/(MAX(HIGH,9)-TSMAX(LOW,9))*100,3,1),3,1)","GTJA_191",1,1,1,"表达式似乎是在尝试构造一个基于价格与波动范围的指标，并通过双重SMA来平滑数据。这样的指标可能用于捕捉价格相对于其波动范围的位置变化。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_029","(CLOSE-DELAY(CLOSE,6))/DELAY(CLOSE,6)*VOLUME","GTJA_191",1,1,1,"将上述的百分比变动与当天的交易量相乘。这样的计算可能用于捕捉价格变动与交易量之间的关系。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_030","WMA((REGRESI(CLOSE/DELAY(CLOSE)-1,MKT,SMB,HML，60))^2,20)","GTJA_191",1,1,1,"这个表达式首先计算了收益率与MKT, SMB, HML三个因子的回归系数，并将这个系数取平方，然后对这个平方值进行20期的加权移动平均。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_031","(CLOSE-MEAN(CLOSE,12))/MEAN(CLOSE,12)*100","GTJA_191",1,1,1,"表达式计算的是当天收盘价相对于其过去12天平均收盘价的百分比变动。这种百分比变动可以用于分析股票价格的短期波动情况。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_032","(-1 * SUM(RANK(CORR(RANK(HIGH), RANK(VOLUME), 3)), 3))","GTJA_191",1,1,1,"表达式似乎是在尝试计算某种基于最高价排名、交易量排名以及它们之间相关系数排名的复杂指标，并可能涉及某种窗口计算。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_033"," ((((-1 * TSMIN(LOW, 5)) + DELAY(TSMIN(LOW, 5), 5)) * RANK(((SUM(RET, 240) - SUM(RET, 20)) / 220))) * TSRANK(VOLUME, 5))","GTJA_191",1,1,1,"可能用于捕捉价格变动、收益率差异以及交易量排名之间的关系，从而帮助投资者或分析师识别市场趋势或交易机会。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_034"," MEAN(CLOSE,12)/CLOSE","GTJA_191",1,1,1,"计算了12日移动平均值与当日收盘价的比值。这个比值可以帮助投资者了解当前价格相对于其最近12日平均价格的位置。例如，如果比值为1.05，那么意味着当前的收盘价略高于其12日平均收盘价；如果比值为0.95，则意味着当前的收盘价略低于其12日平均收盘价。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_035"," (MIN(RANK(DECAYLINEAR(DELTA(OPEN, 1), 15)), RANK(DECAYLINEAR(CORR((VOLUME), ((OPEN * 0.65) + (OPEN *0.35)), 17),7))) * -1)","GTJA_191",1,1,1,"公式结合了开盘价变动的排名、交易量与价格组合的相关性的排名,二者最小值，结果乘以-1。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_036","RANK(SUM(CORR(RANK(VOLUME), RANK(VWAP)), 6), 2)","GTJA_191",1,1,1,"公式成交量和VWAP(成交量加权平均价)相关性之后的排名值。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_037","(-1 * (RANK((SUM(OPEN, 5) * SUM(RET, 5)) - DELAY((SUM(OPEN, 5) * SUM(RET, 5)), 10))))","GTJA_191",1,1,1,"公式开盘价的总和与收益率的总和相乘的排名减去10日之前的值取反。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_038","(((SUM(HIGH, 20) / 20) < HIGH) ? (-1 * DELTA(HIGH, 2)) : 0)","GTJA_191",1,1,1,"如果当前周期的最高价突破了最近20个周期的最高价的平均值，则计算当前最高价与两个周期前最高价之间的反向差值；否则，返回0。这种逻辑可能用于检测价格突破，并据此生成交易信号或分析价格动态。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_039","((RANK(DECAYLINEAR(DELTA((CLOSE), 2),8)) - RANK(DECAYLINEAR(CORR(((VWAP * 0.3) + (OPEN * 0.7)), SUM(MEAN(VOLUME,180), 37), 14), 12))) * -1)","GTJA_191",1,1,1,"表达式结合了价格变动、成交量、相关性以及排名的概念，可能用于某种复杂的交易策略或市场分析中。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_040","SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:0),26)/SUM((CLOSE<=DELAY(CLOSE,1)?VOLUME:0),26)*100","GTJA_191",1,1,1,"整个表达式的意义在于计算一个反映价格变动与成交量关系的指标。当价格上涨时，与之对应的成交量可能被认为是更有力的，因为上涨通常伴随着买盘的增加。通过计算上涨时和下跌/持平时成交量的比率，投资者可以获取关于市场情绪的额外信息，这可能有助于交易决策。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_041","(RANK(MAX(DELTA((VWAP), 3), 5))* -1)","GTJA_191",1,1,1,"表达式可能用于检测VWAP的短期变动是否达到了一个相对较高的水平，并通过排名和反向操作来量化这种变动。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_042","((-1 * RANK(STD(HIGH, 10))) * CORR(HIGH, VOLUME, 10))","GTJA_191",1,1,1,"表达式可能用于检测最高价的波动情况（通过标准差衡量）与最高价和成交量之间关系（通过相关性衡量）的综合效果。如果最高价的波动较大（标准差较高），并且这种波动与成交量的变化存在较强的正相关（即成交量随着价格波动而增加），则整个表达式的值可能较大。这种指标可能有助于交易者识别价格波动的强度和成交量的响应情况，从而辅助交易决策");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_043","SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:(CLOSE<DELAY(CLOSE,1)?-VOLUME:0)),6)","GTJA_191",1,1,1,"表整个表达式的意义在于计算一个基于价格变动和成交量的累积值。价格上涨时的成交量被直接累加，而价格下跌时的成交量则以相反数形式累加，这实际上是在减少总和。如果价格上涨的成交量大于价格下跌的成交量，则整个表达式的值将是正数，反之为负数。这个累积值可能用于评估市场的买卖力量对比，有助于交易者识别市场的趋势和动力。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_044","(TSRANK(DECAYLINEAR(CORR(((LOW )), MEAN(VOLUME,10), 7), 6),4) + TSRANK(DECAYLINEAR(DELTA((VWAP),3), 10), 15))","GTJA_191",1,1,1,"整体来看，这个表达式似乎用于综合评估两个不同方面的市场情况：一个是最低价与成交量均值之间的相关性及其动态变化，另一个是VWAP的短期变动及其动态变化。通过将这两个方面的排名值相加，可能得到一个反映市场某些特性的综合度量。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_045","(RANK(DELTA((((CLOSE * 0.6) + (OPEN *0.4))), 1)) * RANK(CORR(VWAP, MEAN(VOLUME,150), 15)))","GTJA_191",1,1,1,"表达式似乎旨在通过结合加权价格的短期变动和VWAP与成交量均值之间的长期相关性来产生一个综合指标。加权价格的变动可能反映了价格的短期动态，而VWAP与成交量均值的相关性则可能反映了市场的长期趋势或结构。通过将这两个方面的排名值相乘，可能得到一个既考虑短期变动又考虑长期趋势的综合度量。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_046","(MEAN(CLOSE,3)+MEAN(CLOSE,6)+MEAN(CLOSE,12)+MEAN(CLOSE,24))/(4*CLOSE)","GTJA_191",1,1,1,"计算一个相对强度指标，它比较了不同时间周期内的平均收盘价与当前收盘价的相对大小。如果结果大于1，那么这可能意味着过去几个周期的平均收盘价高于当前收盘价，这可能是一个买入信号；如果结果小于1，那么可能意味着过去几个周期的平均收盘价低于当前收盘价，这可能是一个卖出信号。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_047","SMA((TSMAX(HIGH,6)-CLOSE)/(TSMAX(HIGH,6)-TSMIN(LOW,6))*100,9,1)","GTJA_191",1,1,1,"表达式可能用于创建一个指标，该指标反映了当前收盘价相对于过去一段时间内的价格范围的相对位置，并通过简单移动平均进行了平滑处理。这样的指标可能有助于交易者识别价格相对于其近期范围的强度或弱点，从而辅助交易决策。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_048","(-1*((RANK(((SIGN((CLOSE - DELAY(CLOSE, 1))) + SIGN((DELAY(CLOSE, 1) - DELAY(CLOSE, 2)))) + SIGN((DELAY(CLOSE, 2) - DELAY(CLOSE, 3)))))) * SUM(VOLUME, 5)) / SUM(VOLUME, 20))","GTJA_191",1,1,1,"表达式似乎旨在结合价格变动的方向和成交量来创建一个指标。通过检查连续周期的价格变动是否一致，并使用成交量进行加权和归一化，这个指标可能反映了市场趋势的强度和一致性。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_049","SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)) ","GTJA_191",1,1,1,"表达式可能试图衡量价格变动的幅度，特别是当当前周期的价格范围小于或等于前一个周期的价格范围时。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_050","SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))-SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))","GTJA_191",1,1,1,"表达式可能试图衡量价格变动的幅度和方向，特别是关注当前周期价格范围与前一个周期价格范围的关系。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_051","SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)/(SUM(((HIGH+LOW)<=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12)+SUM(((HIGH+LOW)>=(DELAY(HIGH,1)+DELAY(LOW,1))?0:MAX(ABS(HIGH-DELAY(HIGH,1)),ABS(LOW-DELAY(LOW,1)))),12))  ","GTJA_191",1,1,1,"这个表达式可能用于计算某种价格变动的指标，特别是关注当前周期价格范围与前一个周期价格范围的关系。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_052","SUM(MAX(0,HIGH-DELAY((HIGH+LOW+CLOSE)/3,1)),26)/SUM(MAX(0,DELAY((HIGH+LOW+CLOSE)/3,1)-LOW),26)*100 ","GTJA_191",1,1,1,"表达式计算的是一个基于价格变动的指标，它比较了当前周期的最高价与前一个周期平均价格的差异，并与前一个周期平均价格与当前周期最低价的差异进行比较。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_053","COUNT(CLOSE>DELAY(CLOSE,1),12)/12*100","GTJA_191",1,1,1,"整个表达式的意义是计算过去12个周期内，平均每天收盘价上涨的百分比。这个指标可以反映股价在过去一段时间内的上涨趋势或上涨的频率。如果结果接近100%，说明过去12天几乎每天都在上涨；如果接近0%，则说明几乎没有上涨。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_054","(-1 * RANK((STD(ABS(CLOSE - OPEN)) + (CLOSE - OPEN)) + CORR(CLOSE, OPEN,10)))","GTJA_191",1,1,1,"这个表达式可能用于分析股票价格变化的标准偏差、绝对变化量以及收盘价与开盘价之间的线性关系，并将这些因素结合成一个单一的指标。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_055","SUM(16*(CLOSE-DELAY(CLOSE,1)+(CLOSE-OPEN)/2+DELAY(CLOSE,1)-DELAY(OPEN,1))/((ABS(HIGH-DELAY(CLOSE,1))>ABS(LOW-DELAY(CLOSE,1)) & ABS(HIGH-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1))?ABS(HIGH-DELAY(CLOSE,1))+ABS(LOW-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:(ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(LOW,1)) & ABS(LOW-DELAY(CLOSE,1))>ABS(HIGH-DELAY(CLOSE,1))?ABS(LOW-DELAY(CLOSE,1))+ABS(HIGH-DELAY(CLOSE,1))/2+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4:ABS(HIGH-DELAY(LOW,1))+ABS(DELAY(CLOSE,1)-DELAY(OPEN,1))/4)))*MAX(ABS(HIGH-DELAY(CLOSE,1)),ABS(LOW-DELAY(CLOSE,1))),20) ","GTJA_191",1,1,1,"表达式是一个相对复杂的金融分析指标，用于计算一种基于价格变动的加权和。它考虑了开盘价、收盘价、最高价和最低价等多个因素，并使用了延迟函数和条件判断。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_056","(RANK((OPEN - TSMIN(OPEN, 12))) < RANK((RANK(CORR(SUM(((HIGH + LOW) / 2), 19), SUM(MEAN(VOLUME,40), 19), 13))^5)))  ","GTJA_191",1,1,1,"比较“开盘价与过去12个周期最低开盘价的差值的排名”与“相关系数排名的五次方”的大小。如果前者小于后者，整个表达式的结果为真（或1），否则为假（或0）。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_057","SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1)","GTJA_191",1,1,1,"表达式计算了一个反映当前收盘价在过去9个周期价格范围内相对位置的指标，并且通过3周期的简单移动平均进行了平滑处理。这样的指标可能用于识别价格相对于其近期范围的强弱，有助于投资者判断市场的趋势和买卖点。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_058","COUNT(CLOSE>DELAY(CLOSE,1),20)/20*100 ","GTJA_191",1,1,1,"表达式计算了过去20个周期内收盘价上涨的比例，并将其转化为百分比。这个百分比指标可能用于评估市场的上涨趋势或股票的强势程度。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_059","SUM((CLOSE=DELAY(CLOSE,1)?0:CLOSE-(CLOSE>DELAY(CLOSE,1)?MIN(LOW,DELAY(CLOSE,1)):MAX(HIGH,DELAY(CLOSE,1)))),20)  ","GTJA_191",1,1,1,"表达式计算了过去20个周期内的一个累计值。当当前周期的收盘价等于前一个周期的收盘价时，累计值不增加；当当前收盘价上涨时，累计值增加当前收盘价与过去最低价（或前一个周期收盘价）之间的差值；当当前收盘价下跌时，累计值减少当前收盘价与过去最高价（或前一个周期收盘价）之间的差值。这样的指标可能用于捕捉价格变动的累积效应，对于分析价格趋势和动量有一定的参考价值。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_060"," SUM(((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW)*VOLUME,20)  ","GTJA_191",1,1,1,"用于计算过去20个周期内价格变动与成交量的加权累计值。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_061"," (MAX(RANK(DECAYLINEAR(DELTA(VWAP, 1), 12)),RANK(DECAYLINEAR(RANK(CORR((LOW),MEAN(VOLUME,80), 8)), 17))) * -1)","GTJA_191",1,1,1,"这个表达式结合了VWAP变化量的排名、最低价与平均成交量的相关性排名，以及线性衰减函数。通过这种方式，它可能用于捕捉价格与成交量之间的动态关系，同时考虑到不同时间段的权重差异。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_062","(-1 * CORR(HIGH, RANK(VOLUME), 5))","GTJA_191",1,1,1,"这个表达式计算的是过去5个周期内最高价与排名后的成交量之间的负相关系数，并且将这个负相关系数反转为其对应的正相关系数。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_063"," SMA(MAX(CLOSE-DELAY(CLOSE,1),0),6,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),6,1)*100","GTJA_191",1,1,1,"这个表达式计算了收盘价上升的比例（相对于其总的变化量）的6周期简单移动平均值，并以百分比形式表示。这种指标可能用于分析价格的动量或趋势强度，帮助投资者判断市场的买入或卖出信号。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_064"," (MAX(RANK(DECAYLINEAR(CORR(RANK(VWAP), RANK(VOLUME), 4), 4)),RANK(DECAYLINEAR(MAX(CORR(RANK(CLOSE), RANK(MEAN(VOLUME,60)), 4), 13), 14))) * -1)","GTJA_191",1,1,1,"表达式似乎是在尝试通过一系列复杂的计算和排名过程来捕捉价格（VWAP和CLOSE）与成交量（VOLUME）之间的某种关系或趋势。通过结合相关系数、排名、线性衰减和最大值函数，它可能旨在生成一个能够反映市场动量、趋势或交易信号的指标。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_065"," (MAX(RANK(DECAYLINEAR(CORR(RANK(VWAP), RANK(VOLUME), 4), 4)),RANK(DECAYLINEAR(MAX(CORR(RANK(CLOSE), RANK(MEAN(VOLUME,60)), 4), 13), 14))) * -1)","GTJA_191",1,1,1,"表达式将上述计算的6周期收盘价的均值除以当前周期的收盘价，得到一个比率。这个比率可以解释为当前收盘价相对于过去6个交易日平均收盘价的水平。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_066"," (CLOSE-MEAN(CLOSE,6))/MEAN(CLOSE,6)*100","GTJA_191",1,1,1,"表达式将上述计算的6周期收盘价的均值除以当前周期的收盘价，得到一个比率。这个比率可以解释为当前收盘价相对于过去6个交易日平均收盘价的水平。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_067","  SMA(MAX(CLOSE-DELAY(CLOSE,1),0),24,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),24,1)*100 ","GTJA_191",1,1,1,"表达式计算了价格上涨部分相对于总价格变动的百分比，并使用了24周期的简单移动平均线进行平滑处理。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_068"," SMA(((HIGH+LOW)/2-(DELAY(HIGH,1)+DELAY(LOW,1))/2)*(HIGH-LOW)/VOLUME,15,2) ","GTJA_191",1,1,1,"表达式计算了一个结合了典型价格变动、价格范围与成交量比值的指标，并使用了15周期的简单移动平均线进行平滑处理。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_069"," (SUM(DTM, 20) > SUM(DBM, 20) ? (SUM(DTM, 20) - SUM(DBM, 20)) / SUM(DTM, 20) : (SUM(DTM, 20) = SUM(DBM, 20) ? 0 : (SUM(DTM, 20) - SUM(DBM, 20)) / SUM(DBM, 20)))","GTJA_191",1,1,1,"DTM = (OPEN<=DELAY(OPEN,1)?0:MAX((HIGH-OPEN),(OPEN-DELAY(OPEN,1)))  DBM = (OPEN>=DELAY(OPEN,1)?0:MAX((OPEN-LOW),(OPEN-DELAY(OPEN,1)))) 表达式可以用于判断价格动量的强度和方向。当 DTM 的累计和大于 DBM 的累计和时，可能表明市场上涨动量较强；当两者相等时，市场可能处于平衡状态；当 DTM 的累计和小于 DBM 的累计和时，可能表明市场下跌动量较强。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_070","STD(AMOUNT, 6)","GTJA_191",1,1,1,"计算的是 AMOUNT 数据序列中最近6个数据点的标准差。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_071"," (CLOSE-MEAN(CLOSE,24))/MEAN(CLOSE,24)*100","GTJA_191",1,1,1,"表达式的值是一个百分比，它表示当前收盘价相对于其过去24个交易日的平均值偏离了多少百分比。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_072","SMA((TSMAX(HIGH,6)-CLOSE)/(TSMAX(HIGH,6)-TSMIN(LOW,6))*100,15,1)","GTJA_191",1,1,1,"表达式计算了一个衡量当前收盘价相对于过去6个周期价格范围的位置的百分比指标，并通过一个15周期的简单移动平均线进行了平滑处理。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_073","((TSRANK(DECAYLINEAR(DECAYLINEAR(CORR((CLOSE), VOLUME, 10), 16), 4), 5) - RANK(DECAYLINEAR(CORR(VWAP, MEAN(VOLUME,30), 4),3))) * -1) ","GTJA_191",1,1,1,"表达式的最终结果是两个排名之间的差异（经过一些调整），它可能用于比较不同指标之间的相对强度或趋势。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_074","(RANK(CORR(SUM(((LOW * 0.35) + (VWAP * 0.65)), 20), SUM(MEAN(VOLUME,40), 20), 7)) + RANK(CORR(RANK(VWAP), RANK(VOLUME), 6)))","GTJA_191",1,1,1,"表达式可能用于衡量价格与成交量之间的关系，以及VWAP与VOLUME之间的相对变化。");  
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_075","COUNT(CLOSE>OPEN & BANCHMARKINDEXCLOSE<BANCHMARKINDEXOPEN,50)/COUNT(BANCHMARKINDEXCLOSE<BANCHMARKINDEXOPEN,50)","GTJA_191",1,1,1,"表达式计算两个计数的比值。这个比值表示在过去50个交易日中，当基准指数下跌时，个股收盘价上涨的交易日所占的比例。这个比例可能用于评估个股相对于基准指数的表现强度或抗跌性。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_076","STD(ABS((CLOSE/DELAY(CLOSE,1)-1))/VOLUME,20)/MEAN(ABS((CLOSE/DELAY(CLOSE,1)-1))/VOLUME,20)","GTJA_191",1,1,1,"表达式通过计算过去 20 天内归一化价格变化的标准差与平均值的比值，来评估股票或其他金融产品的价格波动性。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_077","MIN(RANK(DECAYLINEAR(((((HIGH + LOW) / 2) + HIGH)  -  (VWAP + HIGH)), 20)), RANK(DECAYLINEAR(CORR(((HIGH + LOW) / 2), MEAN(VOLUME,40), 3), 6)))","GTJA_191",1,1,1,"表达式通过计算价格偏离度和价格与成交量的相关性，并给出它们的加权排名，为投资者提供了一个综合分析股票表现的指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_078","((HIGH+LOW+CLOSE)/3-MA((HIGH+LOW+CLOSE)/3,12))/(0.015*MEAN(ABS(CLOSE-MEAN((HIGH+LOW+CLOSE)/3,12)),12))","GTJA_191",1,1,1,"表达式计算的是一个标准化后的价格偏离度指标，它结合了典型价格、移动平均和价格变动的平均绝对值等多个因素。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_079","SMA(MAX(CLOSE-DELAY(CLOSE,1),0),12,1)/SMA(ABS(CLOSE-DELAY(CLOSE,1)),12,1)*100","GTJA_191",1,1,1,"表达式计算了一个反映股票价格上涨趋势强度和持续性的百分比指标。这个指标可以帮助投资者了解股票在一段时间内的表现，特别是其上涨的动力和稳定性。如果这个百分比较高，可能意味着股票在这段时间内有较强的上涨趋势；反之，如果百分比较低，可能意味着上涨动力不足或存在较大的价格波动。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_080","(VOLUME-DELAY(VOLUME,5))/DELAY(VOLUME,5)*100","GTJA_191",1,1,1,"表达式的结果是一个百分比值，它告诉我们当前交易量比5天前增加了多少或减少了多少。如果结果是正数，表示交易量增加了；如果是负数，表示交易量减少了。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_081","SMA(VOLUME,21,2)","GTJA_191",1,1,1,"计算一个简单移动平均,aplha=2/21.");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_082","SMA((TSMAX(HIGH,6)-CLOSE)/(TSMAX(HIGH,6)-TSMIN(LOW,6))*100,20,1)","GTJA_191",1,1,1,"表达式计算了一个反映当前收盘价相对于最近6天价格波动范围的相对位置的指标，并通过20日的简单移动平均进行了平滑处理。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_083","(-1 * RANK(COVIANCE(RANK(HIGH), RANK(VOLUME), 5)))","GTJA_191",1,1,1,"公式似乎试图衡量最高价排名与成交额排名之间的协方差，并对这个协方差进行排名，然后逆转排名的顺序。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_084","SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:(CLOSE<DELAY(CLOSE,1)?-VOLUME:0)),20)","GTJA_191",1,1,1,"表达式计算的是过去20个交易日中，每当今日收盘价高于昨日收盘价时，累加当日交易量；每当今日收盘价低于昨日收盘价时，累加当日交易量的负值。最终得到的是一个反映价格变动和交易量之间关系的累积指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_085"," (TSRANK((VOLUME / MEAN(VOLUME,20)), 20) * TSRANK((-1 * DELTA(CLOSE, 7)), 8)) ","GTJA_191",1,1,1,"这个表达式将两个排名相乘：一个是基于交易量相对于平均交易量的比值，另一个是基于价格变动的方向。相乘的结果可能是一个介于0和1之间的值，它综合了交易量的相对大小和价格变动的方向两个因素。如果两者都是高排名（即交易量大且价格下降或交易量小且价格上升），则结果将接近1；如果两者都是低排名，则结果将接近0"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_086","((0.25 < (((DELAY(CLOSE, 20) - DELAY(CLOSE, 10)) / 10) - ((DELAY(CLOSE, 10) - CLOSE) / 10))) ? (-1 * 1) : (((((DELAY(CLOSE, 20) - DELAY(CLOSE, 10)) / 10) - ((DELAY(CLOSE, 10) - CLOSE) / 10)) < 0) ? 1 : ((-1 * 1) *(CLOSE - DELAY(CLOSE, 1)))))","GTJA_191",1,1,1,"表达式可能用于识别价格趋势的变化，特别是当价格在不同时间段内表现出不同的变动模式时。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_087","((RANK(DECAYLINEAR(DELTA(VWAP, 4), 7)) + TSRANK(DECAYLINEAR(((((LOW * 0.9) + (LOW * 0.1)) - VWAP) / (OPEN - ((HIGH + LOW) / 2))), 11), 7)) * -1) ","GTJA_191",1,1,1,"表达式结合了对VWAP变动的考虑、价格的相对位置以及线性衰减与排名的应用，可能是为了创建一个综合考虑了价格动态、成交量以及时间衰减的复合指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_088"," (CLOSE-DELAY(CLOSE,20))/DELAY(CLOSE,20)*100","GTJA_191",1,1,1,"表达式计算了从20天前到现在，收盘价变化的百分比。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_089"," 2*(SMA(CLOSE,13,2)-SMA(CLOSE,27,2)-SMA(SMA(CLOSE,13,2)-SMA(CLOSE,27,2),10,2))","GTJA_191",1,1,1,"表达式可能用于检测短期和长期趋势之间的差异，并尝试捕捉这种差异的变化速度。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_090"," ( RANK(CORR(RANK(VWAP), RANK(VOLUME), 5)) * -1) ","GTJA_191",1,1,1,"表达式首先计算了 VWAP 和 VOLUME 的排名之间的相关系数，然后对这个相关系数进行了排名，并乘以 -1。这个指标可能用于分析价格和成交量之间的相关性，并尝试捕捉这种相关性在时间序列上的变化。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_091"," ((RANK((CLOSE - MAX(CLOSE, 5)))*RANK(CORR((MEAN(VOLUME,40)), LOW, 5))) * -1) ","GTJA_191",1,1,1,"表达式可能用于分析当前价格相对于近期高点的位置，并结合成交量均值与最低价之间的相关性，来生成一个综合指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_092"," (MAX(RANK(DECAYLINEAR(DELTA(((CLOSE * 0.35) + (VWAP *0.65)), 2), 3)), TSRANK(DECAYLINEAR(ABS(CORR((MEAN(VOLUME,180)), CLOSE, 13)), 5), 15)) * -1)","GTJA_191",1,1,1,"表达式结合了价格与成交量加权平均价的加权和的变化量、成交量均值与收盘价之间的相关性，并通过排名和线性衰减等方法进行处理，最终得到一个综合指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_093","SUM((OPEN>=DELAY(OPEN,1)?0:MAX((OPEN-LOW),(OPEN-DELAY(OPEN,1)))),20)","GTJA_191",1,1,1,"表达式的目的是计算过去20天内，当日的开盘价低于前一日的开盘价时，开盘价与最低价或前一日开盘价之间的最大差值的累加和。这可能用于识别开盘价的下跌趋势或力度，并可能作为交易策略或分析的一部分。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_094"," SUM((CLOSE>DELAY(CLOSE,1)?VOLUME:(CLOSE<DELAY(CLOSE,1)?-VOLUME:0)),30) ","GTJA_191",1,1,1,"表达式的目的是计算过去30天内，当日的收盘价相对于前一日收盘价发生变化时，对应的“加权”成交量的累加和。如果收盘价上涨，则计入正成交量；如果收盘价下跌，则计入负成交量；如果收盘价不变，则不计入。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_095","STD(AMOUNT,20) ","GTJA_191",1,1,1,"表达式计算20天成交额的标准差。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_096","SMA(SMA((CLOSE-TSMIN(LOW,9))/(TSMAX(HIGH,9)-TSMIN(LOW,9))*100,3,1),3,1) ","GTJA_191",1,1,1,"表达式计算了一个基于收盘价与过去9天内的最高价和最低价之间关系的双重平滑指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_097","STD(VOLUME,10)","GTJA_191",1,1,1,"表达式计算10天成交量的标准差。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_098","((((DELTA((SUM(CLOSE, 100) / 100), 100) / DELAY(CLOSE, 100)) < 0.05) || ((DELTA((SUM(CLOSE, 100) / 100), 100) / DELAY(CLOSE, 100)) == 0.05)) ? (-1 * (CLOSE - TSMIN(CLOSE, 100))) : (-1 * DELTA(CLOSE, 3)))","GTJA_191",1,1,1,"表达式似乎是在检查过去100天收盘价的平均值相对于100天前的变化率是否较小（小于或等于5%）。如果是这样，则计算当前收盘价与过去100天最低收盘价之差的相反数；否则，计算当前收盘价与3天前收盘价之差的相反数。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_099","(-1 * RANK(COVIANCE(RANK(CLOSE), RANK(VOLUME), 5)))","GTJA_191",1,1,1,"表达式可能用于识别收盘价排名和成交量排名之间的协方差在特定周期内的相对变化。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_100"," STD(VOLUME,20)","GTJA_191",1,1,1,"表达式计算20天成交量的标准差。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_101"," ((RANK(CORR(CLOSE, SUM(MEAN(VOLUME,30), 37), 15)) < RANK(CORR(RANK(((HIGH * 0.1) + (VWAP * 0.9))), RANK(VOLUME), 11))) * -1)","GTJA_191",1,1,1,"如果第一个排名小于第二个排名，则整个表达式的结果为-1；否则，结果为0。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_102","SMA(MAX(VOLUME-DELAY(VOLUME,1),0),6,1)/SMA(ABS(VOLUME-DELAY(VOLUME,1)),6,1)*100","GTJA_191",1,1,1,"成交量增加量的6日简单移动平均值除以成交量变化量绝对值的6日简单移动平均值，并将结果乘以100，得到一个百分比。这个百分比表示了成交量增加的情况相对于总成交量变化的比例。如果这个比例较高，可能意味着市场有更多的买入力量；如果较低，可能意味着市场有更多的卖出力量或交易较为平衡"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_103","((20-LOWDAY(LOW,20))/20)*100","GTJA_191",1,1,1,"指标可能用于衡量当前价格相对于过去20天最低价的位置。如果结果接近100%，说明当前价格远高于过去20天的最低价；如果结果接近0%，说明当前价格接近或就是过去20天的最低价。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_104","(-1 * (DELTA(CORR(HIGH, VOLUME, 5), 5) * RANK(STD(CLOSE, 20))))","GTJA_191",1,1,1,"表达式可能用于识别最高价和成交量之间相关性的变化，并结合收盘价的标准差排名来生成某种交易信号或指标"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_105","(-1 * CORR(RANK(OPEN), RANK(VOLUME), 10))","GTJA_191",1,1,1,"表达式可能用于识别开盘价和成交量之间排名的相关性。通过计算相关系数并乘以-1，可能生成某种交易信号或指标，但这需要结合实际的交易策略和市场分析来理解和使用。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_106","CLOSE-DELAY(CLOSE,20)","GTJA_191",1,1,1,"表达式计算收盘价和20天前收盘价的绝对差值。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_107","(((-1 * RANK((OPEN - DELAY(HIGH, 1)))) * RANK((OPEN - DELAY(CLOSE, 1)))) * RANK((OPEN - DELAY(LOW, 1))))","GTJA_191",1,1,1,"表达式可能用于识别开盘价相对于前一日最高价、收盘价和最低价的相对位置，并通过排名和乘法运算来生成某种交易信号或指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_108","((RANK((HIGH - MIN(HIGH, 2)))^RANK(CORR((VWAP), (MEAN(VOLUME,120)), 6))) * -1) ","GTJA_191",1,1,1,"表达式可能用于识别最高价相对于其短期最低值的相对位置，并结合 VWAP 和成交量平均值之间的相关性来生成某种交易信号或指标。"); 
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_109","SMA(HIGH-LOW,10,2)/SMA(SMA(HIGH-LOW,10,2),10,2)","GTJA_191",1,1,1,"表达式可能用于识别价格范围的长期趋势与短期趋势之间的关系。通过比较不同周期内的价格范围移动平均，交易者可以判断市场是否处于趋势中，或者是否出现了趋势的逆转。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_110","SUM(MAX(0,HIGH-DELAY(CLOSE,1)),20)/SUM(MAX(0,DELAY(CLOSE,1)-LOW),20)*100","GTJA_191",1,1,1,"可能用于衡量某种价格动量或价格范围的指标。具体来说，它计算了最近20个周期内，最高价相对于前一日收盘价的上涨幅度（如果下跌则为0）的总和，与前一日收盘价相对于当前周期最低价的上涨幅度（如果下跌则为0）的总和之间的比率。这个比率可能用于识别价格趋势的强度或方向。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_111","SMA(VOL*((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW),11,2)-SMA(VOL*((CLOSE-LOW)-(HIGH-CLOSE))/(HIGH-LOW),4,2)","GTJA_191",1,1,1,"表达式结合了价格动量、成交量和移动平均线，可能用于识别市场的短期交易机会或趋势变化。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_112","(SUM((CLOSE-DELAY(CLOSE,1)>0?CLOSE-DELAY(CLOSE,1):0),12)-SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12))/(SUM((CLOSE-DELAY(CLOSE,1)>0?CLOSE-DELAY(CLOSE,1):0),12)+SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12))*100 ","GTJA_191",1,1,1,"表达式可能用于衡量一个特定时间段内（这里是12个周期）价格变动的趋势强度。如果百分比值较高，这可能意味着在这个时间段内，价格上涨的力量较强；如果百分比值较低或为负，则可能意味着价格下跌的力量较强或价格主要在下跌。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_113","(-1 * ((RANK((SUM(DELAY(CLOSE, 5), 20) / 20)) * CORR(CLOSE, VOLUME, 2)) * RANK(CORR(SUM(CLOSE, 5), SUM(CLOSE, 20), 2)))) ","GTJA_191",1,1,1,"表达式的具体含义和用途可能依赖于其所在的分析框架和策略。它可能是用于识别价格趋势、动量或交易信号的一部分。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_114","((RANK(DELAY(((HIGH - LOW) / (SUM(CLOSE, 5) / 5)), 2)) * RANK(RANK(VOLUME))) / (((HIGH - LOW) /(SUM(CLOSE, 5) / 5)) / (VWAP - CLOSE))) ","GTJA_191",1,1,1,"整个表达式将分子（波动率排名与成交量排名的乘积）除以分母（调整后的相对波动率指标），得到一个标准化的值。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_115"," (RANK(CORR(((HIGH * 0.9) + (CLOSE * 0.1)), MEAN(VOLUME,30), 10))^RANK(CORR(TSRANK(((HIGH + LOW) / 2), 4), TSRANK(VOLUME, 10), 7)))","GTJA_191",1,1,1,"表达式的具体含义和用途取决于它所处的分析框架和交易策略。它可能用于识别价格动态与成交量之间的复杂关系，并可能用于生成交易信号或评估市场状况。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_116","  REGBETA(CLOSE,SEQUENCE,20)","GTJA_191",1,1,1,"表达式看起来像是在调用一个名为 REGBETA 的函数，该函数可能用于计算某种回归分析中的β系数。具体来说，它可能是在分析收盘价（CLOSE）与某个序列（SEQUENCE）之间的关系，并且这个分析是基于20个数据点或周期进行的。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_117"," ((TSRANK(VOLUME, 32) * (1 - TSRANK(((CLOSE + HIGH) - LOW), 16))) * (1 - TSRANK(RET, 32)))","GTJA_191",1,1,1,"表达式首先将成交量的时间序列排名与价格范围排名差异相乘，然后将结果与回报率排名差异相乘。这样的组合可能用于识别成交量与价格波动性以及回报率之间的复杂关系。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_118"," SUM(HIGH-OPEN,20)/SUM(OPEN-LOW,20)*100","GTJA_191",1,1,1,"表达式的意义可能在于衡量价格波动的不同方面。分子部分（最高价与开盘价之差）可能代表价格的上涨动力或日内波动性，而分母部分（开盘价与最低价之差）可能代表价格的下跌空间或日内波动性的下限。整个表达式的值可能用于识别价格的相对强度或评估市场的趋势和波动性。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_119"," (RANK(DECAYLINEAR(CORR(VWAP, SUM(MEAN(VOLUME,5), 26), 5), 7)) -RANK(DECAYLINEAR(TSRANK(MIN(CORR(RANK(OPEN), RANK(MEAN(VOLUME,15)), 21), 9), 7), 8)))","GTJA_191",1,1,1,"可能用于捕捉价格与成交量之间的动态关系，并可能用于预测价格走势或生成交易信号。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_120","  (RANK((VWAP - CLOSE)) / RANK((VWAP + CLOSE)))","GTJA_191",1,1,1,"表达式的意义可能在于通过比较价格差异和价格总和的排名来识别市场的某种特定模式或行为。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_121","((RANK((VWAP - MIN(VWAP, 12)))^TSRANK(CORR(TSRANK(VWAP, 20), TSRANK(MEAN(VOLUME,60), 2), 18), 3)) * -1) ","GTJA_191",1,1,1,"表达式的意义可能在于通过结合价格（VWAP）和成交量（MEAN(VOLUME, 60)）的时间序列排名及其相关性，来识别市场的某种特定模式或行为。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_122","(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2)-DELAY(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2),1))/DELAY(SMA(SMA(SMA(LOG(CLOSE),13,2),13,2),13,2),1) ","GTJA_191",1,1,1,"表达式的整体意义可能在于通过计算对数价格的多层嵌套简单移动平均，并比较当前值与过去值之间的差异，来识别价格的动态变化或趋势。比率值可能用于衡量当前价格动量或趋势的强度，并可能作为交易决策的一部分。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_123","((RANK(CORR(SUM(((HIGH + LOW) / 2), 20), SUM(MEAN(VOLUME,60), 20), 9)) < RANK(CORR(LOW, VOLUME, 6))) * -1) ","GTJA_191",1,1,1,"表达式的意义可能在于通过比较两种不同价格指标（中间价和与最低价）与成交量之间的相关性排名，来识别市场的某种特定模式或行为。如果中间价和与成交量的相关性排名较低，而最低价与成交量的相关性排名较高，这可能意味着当前市场存在某种特定的价格与成交量关系，可能是一个交易信号或需要进一步分析的线索。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_124","(CLOSE - VWAP) / DECAYLINEAR(RANK(TSMAX(CLOSE, 30)),2)","GTJA_191",1,1,1,"表达式的意义可能在于通过结合价格差异、时间序列最大值以及线性衰减函数，来识别市场的某种特定模式或行为。价格差异与VWAP的比较可能用于衡量价格的强弱，而时间序列最大值和排名则可能用于识别价格趋势或极值。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_125","(RANK(DECAYLINEAR(CORR((VWAP), MEAN(VOLUME,80),17), 20)) / RANK(DECAYLINEAR(DELTA(((CLOSE * 0.5) + (VWAP * 0.5)), 3), 16)))","GTJA_191",1,1,1,"表达式的意义可能在于通过结合价格与成交量的相关性、价格中间值的变化率以及线性衰减函数，来识别市场的某种特定模式或行为。相关性排名可能用于衡量价格与成交量的互动关系，而变化率排名则可能用于识别价格趋势的变动速度。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_126","(CLOSE+HIGH+LOW)/3","GTJA_191",1,1,1,"平均价格通常被称为“典型价格”（Typical Price）或“TP”。典型价格是一个简单但有效的指标，用于表示一个周期内价格的整体水平。它考虑了周期内价格的高点、低点和收盘价，从而提供了一个相对全面的价格视图。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_127","(MEAN((100*(CLOSE-MAX(CLOSE,12))/(MAX(CLOSE,12)))^2))^(1/2)","GTJA_191",1,1,1,"表达式的整体意义在于衡量价格相对于其过去最高点的波动性。通过计算百分比变化、平方、平均值和平方根，它提供了一个平滑且易于解释的度量，用于分析价格的动态变化。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_128","100-(100/(1+SUM(((HIGH+LOW+CLOSE)/3>DELAY((HIGH+LOW+CLOSE)/3,1)?(HIGH+LOW+CLOSE)/3*VOLUME:0),14)/SUM(((HIGH+LOW+CLOSE)/3<DELAY((HIGH+LOW+CLOSE)/3,1)?(HIGH+LOW+CLOSE)/3*VOLUME:0),14)))","GTJA_191",1,1,1,"首先计算上涨时的加权典型价格总和与下跌时的加权典型价格总和的比率，然后用100减去这个比率的倒数。这个计算可能用于衡量市场的上涨动力与下跌动力的相对强度。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_129","SUM((CLOSE-DELAY(CLOSE,1)<0?ABS(CLOSE-DELAY(CLOSE,1)):0),12) ","GTJA_191",1,1,1,"表达式的整体意义在于计算过去12个周期内所有价格下跌时的累计下跌幅度。这种计算方式可以帮助交易者了解价格在这段时间内的下跌趋势和下跌力度，从而可能用于识别市场的弱势或潜在的买入机会。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_130","(RANK(DECAYLINEAR(CORR(((HIGH + LOW) / 2), MEAN(VOLUME,40), 9), 10)) / RANK(DECAYLINEAR(CORR(RANK(VWAP), RANK(VOLUME), 7),3)))","GTJA_191",1,1,1,"表达式的整体意义在于比较两种不同的相关性度量（典型价格与成交量的相关性，以及VWAP与成交量的相关性）的排名，并计算它们的比值。这种比值可能用于评估市场的某种特性或趋势，但具体解释需要结合具体的市场环境和交易策略。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_131","(RANK(DELAT(VWAP, 1))^TSRANK(CORR(CLOSE,MEAN(VOLUME,50), 18), 18))","GTJA_191",1,1,1,"表达式的整体意义可能在于比较VWAP的延迟变化与收盘价和成交量之间的长期关系，并通过排名和幂运算来量化这种比较的结果。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_132","MEAN(AMOUNT,20)","GTJA_191",1,1,1,"计算最近20个周期内AMOUNT的平均值。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_133","((20-HIGHDAY(HIGH,20))/20)*100-((20-LOWDAY(LOW,20))/20)*100","GTJA_191",1,1,1,"表达式的整体意义可能在于衡量过去20天内最高价和最低价出现的频率差异，并以此来判断市场的某种特性或趋势。");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_134","(CLOSE-DELAY(CLOSE,12))/DELAY(CLOSE,12)*VOLUME","GTJA_191",1,1,1,"表达式的整体意义可能在于衡量收盘价在最近12个周期内的变化，并将这种变化与当前的成交量相结合，以得到一个综合指标。 ");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_135","SMA(DELAY(CLOSE/DELAY(CLOSE,20),1),20,1) ","GTJA_191",1,1,1,"表达式的意义可能在于计算一个经过相对变化和延迟调整后的收盘价的简单移动平均。 ");
INSERT INTO `factor_basic_info`(`name`,`desc`,`source`,`type`,`scope`,`status`,`remark`) values ("alpha_136","((-1 * RANK(DELTA(RET, 3))) * CORR(OPEN, VOLUME, 10)) ","GTJA_191",1,1,1,"表达式的整体意义可能在于衡量收益率变化与市场情绪或活跃度之间的综合效应。如果收益率的变化量排名较高（即价格变化显著），并且开盘价与成交量的相关性也较强，那么整个表达式的值可能会较大，这可能意味着市场对该变化有较为积极的反应。 ");